- CHANGELOG.md
- manifest.json
- node/index.ts
- node/package.json
- node/service.json
Recommit the endpoint /enabled
retrocompatibility
[workspace](https://recorrenciaqa.vtexcommercebeta.com.br/_secure/Account/Orders?workspace=felipe#/orders)
> Recommit the endpoint /enabled

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Addresses/AddressFormBox.js
- react/graphql/createAddress.gql
- react/graphql/deleteAddress.gql
- react/graphql/getAddresses.gql
- react/graphql/updateAddress.gql
- Fix 'geoCoordinates' name
- The screen was breaking because name changed.
> Fix 'geoCoordinates' name

- .eslintrc
- CHANGELOG.md
- manifest.json
- package.json
- react/components/Addresses/AddressFormBox.js
- react/graphql/createAddress.gql
- react/graphql/deleteAddress.gql
- react/graphql/getAddresses.gql
- react/graphql/updateAddress.gql
- Add `vtex.my-subscriptions` to the app dependencies
[MyOrders](https://github.com/vtex/my-orders/pull/133)
> Add vtex.my-subscriptions to the app dependencies

- CHANGELOG.md
- manifest.json
- package.json
- Remove MySubscriptions from the dependencies
- [AdminSubscriptions](https://github.com/vtex/admin-subscription-app/pull/4)
> Remove MySubscriptions from the dependencies

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Profile/ProfileBox.js
Fix last name field alignment
Fix last name field alignment
Open any profile on My Account
Before | After
---|---
> Profile last name field alignment

- CHANGELOG.md
- manifest.json
- package.json
- react/components/pages/AddressCreate.js
- react/package.json
- react/yarn.lock
- yarn.lock
Returning to the `returnUrl` if it is present on the url.
> Returning to the `returnUrl` if it is present on the url.

- CHANGELOG.md
- manifest.json
- package.json
ditto.
https://github.com/vtex-apps/my-account/pull/72
> Update the word 'contrasenya' to 'contrassenya'.

- CHANGELOG.md
- manifest.json
- package.json
- react/components/loaders/AddressCreateLoading.js
- react/components/loaders/AddressEditLoading.js
- react/components/loaders/AddressesLoading.js
- react/components/loaders/FormLoader.js
- react/components/loaders/ProfileEditLoading.js
- react/components/loaders/ProfileLoading.js
- ditto.
https://github.com/vtex-apps/my-account-commons/pull/19
> Change Loaders to be consistent with the new api of the `SkeletonPiece` component.

- CHANGELOG.md
- manifest.json
- package.json
- store/interfaces.json
> Allow any app to plugged in into `my-account` abstract interfaces

- CHANGELOG.md
- react/components/Menu/index.js
Add again modal toggle function in the index.js of the menu
The button was not having any action due to the lack modal toggle function
> Fix logout

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Menu/MenuLinksList.js
Title is self-explanatory.
The clients customisation seems to expect the menu links to be in an achor tag.
> Change div to anchor tag to keep customisation compatibility

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Menu/MenuLinksList.js
Reverts vtex-apps/my-account#82
> Revert "Change div to anchor tag to keep customisation compatibility"

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Menu/MenuLinksList.js
Reverts vtex-apps/my-account#83
> Revert "Revert "Change div to anchor tag to keep customisation compatibility""

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Addresses/AddressEditor.js
- ditto.
https://paguemenos.myvtex.com/_secure/account?workspace=sousa
> Fix country fallback on add new address.

- CHANGELOG.md
- react/components/Addresses/AddressBox.js
- react/components/Addresses/AddressDeleter.js
- react/components/Addresses/AddressEditor.js
- react/components/Menu/MenuLinksList.js
- react/components/Menu/ProfilePicture/PictureUploader.js
- react/components/Menu/UserInfo.js
- react/components/Profile/PasswordBox.js
- react/components/Profile/PasswordFormBox.js
- react/components/Profile/PasswordValidator.js
- react/components/Profile/ProfileBox.js
- react/components/Profile/ProfileFormBox.js
- react/components/Profile/RedefinePassword.js
- react/components/shared/ContentBox.js
- react/components/shared/Toast.js
Changed from intl.formatMessage to FormattedMessage component to improve internationalisation.
> Improve Internationalisation

- react/components/AppRouter.js
- react/package.json
- react/yarn.lock
> Fix base tag href

- CHANGELOG.md
- react/components/AppRouter.js
Undo changes made in #93, which are no longer necessary.
Go to [1] and [2] and make sure the my account is opening successfully. There are two links to test the accounts using the portal API and the ones using IO.
[1] https://cobasi.myvtex.com/_secure/account/orders?workspace=arthur#/orders
[2] https://arthur--recorrenciaqa.myvtex.com/account#/orders
> Remove base tag handling

- CHANGELOG.md
- react/components/Menu/ProfilePicture/UserPicture.tsx
> Fix/photo add plus button 1.x

- CHANGELOG.md
- react/components/AppRouter.tsx
- react/typings/global.d.ts
- ditto.
- It would give an error if the vtex wasn't defined.
- Access: https://sousa--recorrenciaqa.myvtex.com/account
> Use window.vtex instead of plain vtex

- CHANGELOG.md
- manifest.json
- package.json
- react/components/AppRouter.tsx
- react/typings/global.d.ts
- ditto.
- It would give an error if the vtex wasn't defined.
- Access: https://sousa--recorrenciaqa.myvtex.com/account
> Use window.vtex instead of plain vtex on v1

- .vscode/settings.json
- CHANGELOG.md
- react/components/Addresses/AddressForm.tsx
> Set the useGeolocation flag when using geolocation 1.x

- CHANGELOG.md
- node/package.json
- node/yarn.lock
- react/components/Profile/NewsletterBox.tsx
- react/components/pages/Profile.tsx
- react/graphql/getNewsletterOpt.gql
- react/graphql/getProfile.gql
- react/package.json
- react/yarn.lock
Changed the query from the parent to its child.
It wasn't updating after going into another tab of my-account.
Before:
After:
https://newsletter--recorrenciaqa.myvtex.com/account#/profile
[[ch34517](https://app.clubhouse.io/vtex/story/34517/opcao-de-newslleter-optin-nao-grava-a-opcao-selecionada)]
> Fix save newsletter

- CHANGELOG.md
- react/components/Menu/index.tsx
Added the Authstate Tag.
The logout needs this tag to work.
https://logout--boticario.myvtex.com/
log in and then try to logout from my-account.
> Fix my-account logout 1.x

- CHANGELOG.md
- react/components/Profile/PasswordFormBox.tsx
Same as #157 but at 0.x
Changed the error to switch by code instead of message.
It was breaking.
https://lojafarm.myvtex.com/_secure/account/orders/?workspace=password#/profile
Try to change your password at my account but misspell your current password, It should show the right message.
> Fix password message

- CHANGELOG.md
- react/components/Addresses/AddressForm.tsx
- react/components/pages/Addresses.tsx
- ditto.
- Log in with: assinaturasqa@mailinator.com
- on: https://felipe--lionspride.myvtex.com/account#/addresses/edit/yajw6lykef
> Fix addresse's edition and listing

- CHANGELOG.md
- manifest.json
- react/components/Profile/ProfileBox.tsx
- react/components/shared/DataEntry.tsx
- react/styles/ContentBox.css
Added css handles for data entry fields within profile section
default classes have a predefined color that customer wants to be changed
inspect data entry rows under my account profile section
https://github.com/vtex-apps/my-account/pull/171/conflicts
> data entry css handles added for profile section

- my-account-extension-example/pages/pages.json
> Fix example link name

- my-account-extension-example/manifest.json
- my-account-extension-example/react/MyAppPage.js
The example code was not updated.
n/a
n/a
> Fix example

- CHANGELOG.md
- manifest.json
- node/index.ts
- node/package.json
- node/service.json
- node/yarn.lock
- Update to node 6
- Tune node server
https://sousa--recorrenciacharlie.myvtex.com/account
> [1.x] Tune node

- CHANGELOG.md
- node/package.json
- node/yarn.lock
- react/components/Addresses/AddressForm.tsx
This PR is the same as https://github.com/vtex-apps/my-account/pull/210 but for version 0.x.
https://vtexgame1geo.myvtex.com/_secure/Account?workspace=arthur#/addresses
Using the workspace above, try to create and edit an address. Both actions should keep working.
> Fix geolocation field cleaning condition

- CHANGELOG.md
- messages/es.json
Fixed the Spanish translation for one string. Tracked in task [LOC-9781](https://vtex-dev.atlassian.net/browse/LOC-9781).
[LOC-9781]: https://vtex-dev.atlassian.net/browse/LOC-9781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix Spanish translation

- CHANGELOG.md
- messages/de.json
This is part of a series of PRs in several apps to make German available across the Admin. Tracked in task [LOC-9843](https://vtex-dev.atlassian.net/browse/LOC-9843).
A test store with DE in the language switcher is [available here](https://localizationqa--obidev.myvtex.com/admin/).
[LOC-9843]: https://vtex-dev.atlassian.net/browse/LOC-9843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add German translations to make it available across Admin.

- CHANGELOG.md
- node/package.json
- node/yarn.lock
- react/components/Addresses/AddressForm.tsx
Improve the country rule on `AddressForm` when use geo location to get account country as default
It was necessary because de old rule to select the country works good when use a dropdown country selector, but don't works with geo location autocomplete
[Workspace](https://wagnerlduarte--eternalhu.myvtex.com/account?__bindingAddress=www.eternal.hu/#/addresses/new)
https://github.com/vtex-apps/my-account/pull/299
> fix address form logic of default country with geo location
