vtex-apps/my-account

- CHANGELOG.md
- react/components/Profile/ProfileFormBox.js
- react/components/pages/ProfileEdit.js
It was not able to update the profile because the email was not being sent to the updateProfile mutation.
[Click here to access the workspace.](https://waza2--storecomponents.myvtex.com/) To test it, go to the account page and try to update the profile informations.
> Fix not updating the profile

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Addresses/AddressFormBox.js
This fixes an error inside address-form accessing `geolocationAutocompleted` of undefined. The undefined value was the missing required prop `addressQuery`.
Open an address form.
> Add required prop addressQuery

- CHANGELOG.md
- manifest.json
- package.json
- react/locales/fr.json
Title is self-explanatory.
French translation for the logout modal title was not correct.
> Fix logout modal title french translation

- react/components/AppRouter.js
Check if exists a base HTML tag before doing any actions with it.
If there wasn't a base tag, the deleteAttribute method would explod when trying to access undefined.
Go to the following workspace and check if My Account is not breaking.
https://www.cobasi.com.br/_secure/account/?workspace=arthur#/cards
> Fix base href attribute deletion to check if there is a base tag before

- CHANGELOG.md
- react/components/Menu/ProfilePicture/PictureUploader.js
- react/components/Profile/PasswordFormBox.js
- react/components/Profile/PasswordValidator.js
- react/components/pages/Profile.js
Corrected some typos when passing props to formatMessage functions.
Because of the typos, required props were undefined and exceptions were thrown.
Use the following workspace and try to upload a profile picture or edit your password.
https://arthur--recorrenciaqa.myvtex.com/account#/profile
* before
* after
> Fix typos in FormattedMessage and intl.formatMessage id param

- CHANGELOG.md
- package.json
- react/SplunkUtils.js
- react/components/Menu/index.js
- react/index.js
- react/package.json
- react/yarn.lock
- yarn.lock
Title is self-explanatory.
Log accounts that use `/account/orders` in its URL in order to map them. Besides, it adds general error logging.
go to [1] and access My Account. Then, go to [2] and check that your access was logged.
[1]: https://cobasi.myvtex.com/_secure/account/orders?workspace=arthur#/cards
[2]: https://splunk7.vtex.com/en-US/app/search/search?q=search%20index%3Dmy_account&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=-5d%40d&latest=now&display.page.search.tab=events&sid=1565298680.90134_D318FDA5-14D0-4248-8853-FBCE1DBB4B96
> Add logging to Splunk for My Account URL and general errors

- CHANGELOG.md
- react/components/Addresses/AddressFormBox.tsx
The `country` of every address being created/edited was being overwritten with the first country the store has shipping to or to `__RUNTIME__.culture.country`. 
For new addresses, this makes sense, but when editing a saved addressed, its saved country value should be used instead.
https://kiwi--beira.myvtex.com/_secure/account?workspace=kiwi#/addresses/new
Clubhouse: https://app.clubhouse.io/vtex/story/19278/pa%C3%ADs-errado-selecionado-ao-editar-um-endere%C3%A7o-j%C3%A1-salvo
Slack: https://vtex.slack.com/archives/CEZQXQJ1Y/p1567100021009800
---
> Prevent country from saved address from being overwritten

- CHANGELOG.md
- react/components/Menu/ProfilePicture/UserPicture.tsx
Explicitly defined the `+` button size (26px/26px), removed default browser padding (`pa0`) and centered the `+` with `flex items-center justify-center`
Safari has some default horizontal `padding` values for `<button>`s:
**Before:**
**After:**
Workspace to test: https://kiwi--recorrenciaqa.myvtex.com/account#/profile
> Fix profile photo plus sign button size on Safari

- .vscode/settings.json
- CHANGELOG.md
- react/components/Addresses/AddressForm.tsx
It explicitly sets the new `useGeolocation` flag to `true` when using geolocation rules.
Continuation of https://github.com/vtex/address-form/pull/218
We were having issues with address forms using geolocation when addresses didn't have a number.
1) https://kiwi--recorrenciaqa.myvtex.com/account#/addresses
2) New address
3) Type av, select an address without a number
4) Type the number on the specified field.
5) Submit
https://app.clubhouse.io/vtex/story/26043/my-account-address-campo-de-n%C3%BAmero-exibindo-referencia-do-object-para-lojas-do-uruguay
> Set the useGeolocation flag when using geolocation

- CHANGELOG.md
- README.md
- manifest.json
- package.json
- react/DefaultPage.tsx
- react/DefaultRoute.tsx
- react/Menu.tsx
In TypeScript to expose a property as `static` you should type them as `static`, not just with `public`. 
With this fix, it's now possible to edit the config of the my account [as is described in the README](https://github.com/vtex-apps/my-account/tree/1.x#defining-the-default-home-page-of-my-account):
https://breno--storecomponents.myvtex.com/admin/app/cms/site-editor/account
Fix https://github.com/vtex-apps/my-account/issues/136
>  Fix Schema

- CHANGELOG.md
- react/components/Profile/ProfileFormBox.tsx
The message was not showing or being translated.
Before:
After:
It was missing the vendor, provider and version to it's id.
Go into https://bianca--paguemenos.myvtex.com/account#/profile/edit
n/a.
> Fix save changes message

- CHANGELOG.md
- react/components/Addresses/AddressForm.tsx
Fixed the message id.
It wasn't showing.
Before:
After:
https://edit--boticario.myvtex.com/account#/addresses/new
> Fix message

- CHANGELOG.md
- react/components/Profile/PasswordFormBox.tsx
Changed the error to switch by code instead of message.
It was breaking.
before:
https://password--storecomponents.myvtex.com/account#/profile
Try to change your password at my account but misspell your current password, It should show the right message.
> Fix password message

- CHANGELOG.md
- react/components/Profile/PasswordFormBox.tsx
Added `toLowerCase` for string comparing on password error.
Its safer.
https://password--storecomponents.myvtex.com/
Try to change your password at my account but misspell your current password, It should show the right message.
> Add to lowercase for string comparing

- CHANGELOG.md
- react/components/Addresses/AddressForm.tsx
- react/components/pages/Addresses.tsx
- ditto.
- same as: https://github.com/vtex-apps/my-account/pull/165
- login on: http://storev1--recorrenciaqa.myvtex.com/
- with assinaturasqa@mailinator.com
- try to edit an address.
> Fix addresse's cache listing and edition on 0.x

- CHANGELOG.md
- react/components/pages/Profile.tsx
Same as #172 but at 1.x
> #### What did you change? \*
> I hid the back button from the profile page.
> 
> #### Why? \*
> It was not going anywhere, therefore it isn't needed.
https://profile--storecomponents.myvtex.com/account#/profile
https://github.com/vtex-apps/my-account-commons/pull/28
> Hide back button @1.x

- CHANGELOG.md
- docs/README.md
- react/components/AppRouter.tsx
- react/components/Profile/ProfileFormBox.tsx
- react/components/pages/ProfileEdit.tsx
- react/index.tsx
A property has been added to the module called blockDocument
The customer needed to block the document field (cpf). Once added, the user should no longer edit. The customer wanted unique accounts per user.
1. Pass the blockDocument property in the declaration of the my-account app in the store
2. Link the vtex.profile-forme app on the tksio-549 branch in the my-account module. It is a dependency.
3. Link the three store / my-account / profile-form repositories and change the property value in the store. By default the speaker is underfid.
If you do not pass the property or pass the false value, the field allows changes.
If it is set to true and the field still has no saved value, the field will also allow editing, if the field is already saved, the field is blocked. …
> Added prop blockDocument to block field in user profile page

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
- node/resolvers/settings.ts
- react/components/Menu/index.tsx
- react/components/shared/withSettings.tsx
- react/graphql/settings.gql
Added `Authentication` toggle to app configurations to set tab visibility 
The `Authentication` tab is a new section of MyAccount that will soon be present in all accounts. We're creating this visibility toggle, for now, to let our customers customize this UI before enabling it.
Go [here](https://rafaprtest--storecomponents.myvtex.com/admin/apps/vtex.my-account@1.19.0/setup/) to access the visibility toggle.
Then go [here](https://rafaprtest--storecomponents.myvtex.com/account#/profile) before and after enabling `Authentication` visibility to check the presence of that section in the left-side menu.
> Feature/idcs 90/show my authentication1x

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
- node/resolvers/settings.ts
- react/components/Menu/index.tsx
- react/components/shared/withSettings.tsx
- react/graphql/settings.gql
Removed `showMyAuthentication` checkbox from [app settings](https://rafaprtest--storecomponents.myvtex.com/admin/apps/vtex.my-account@1.21.0/setup/).
Before
After
Also, added `hideMyAuthentication` setting to the app. This setting is hidden from the [app settings](https://rafaprtest--storecomponents.myvtex.com/admin/apps/vtex.my-account@1.21.0/setup/) UI, but may be set directly through the API.
27/09/2021 will be the end date of the [My Authentication Breaking Change](https://help.vtex.com/pt/announcements/aba-my-authentication-do-my-account--5OETzDR8d5qt13atEBxsB9?utm_source=admin-top-nav). At this date, this should be deployed to force the `my-authentication` UI to appear at every VTEX store.
In case any Store wasn't prepared for the Breaking Change deadline, we will be able to use the …
> Feature/idcs 600/hide my authentication

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
- node/resolvers/settings.ts
- react/components/Menu/MenuLinksList.tsx
- react/components/shared/withSettings.tsx
- react/graphql/settings.gql
Removed `showMyAuthentication` checkbox from [app settings](https://rafaprtest--recorrenciaqa.myvtex.com/admin/apps/vtex.my-account@0.36.0/setup/).
Before
After
Also, added `hideMyAuthentication` setting to the app. This setting is hidden from the [app settings](https://rafaprtest--recorrenciaqa.myvtex.com/admin/apps/vtex.my-account@0.36.0/setup/) UI, but may be set directly through the API.
27/09/2021 will be the end date of the [My Authentication Breaking Change](https://help.vtex.com/pt/announcements/aba-my-authentication-do-my-account--5OETzDR8d5qt13atEBxsB9?utm_source=admin-top-nav). At this date, this should be deployed to force the `my-authentication` UI to appear at every VTEX store.
In case any Store wasn't prepared for the Breaking Change deadline, we will be able to use the new …
> Feature/idcs 599/hide my authentication

- CHANGELOG.md
- manifest.json
- node/package.json
- node/yarn.lock
- react/components/Menu/index.tsx
- react/package.json
- react/typings/global.d.ts
- react/typings/vtex.react-vtexid.d.ts
- react/utils/getRedirectLogout.ts
- react/yarn.lock
Replace client usage for direct call to `/logout` route; remove `vtex.react-vtexid` dependency from project
You can test it at [this workspace](https://rafaprtest2--storecomponents.myvtex.com/account#/profile). Click the MyAccount logout button and check that the logout route is correctly called with an absolute `returnUrl` value. You will see that the redirects correctly occur to the home page, taking `rootPath` into consideration.
> Feature/idcs 834/remove react vtexid

- CHANGELOG.md
- my-account-extension-example/manifest.json
- my-account-extension-example/messages/context.json
- my-account-extension-example/messages/en.json
- my-account-extension-example/react/MyAppLink.js
- Added `store` domain to messages used in `my-account-extension-example`
- Changed small details in `manifest.json` to improve consistency in the boilerplate code
I was getting this error from builder hub:
1. Copy the code for the example like this: 
``` 
npx degit 'vtex-apps/my-account/my-account-extension-example#fix/1.x/my-account-extension-example' vtex.my-account-extension-example
````
2. Run `vtex link` in a development workspace
3. You should no longer see the builder hub error
I started investigating this because of this VTEX Community question:
https://community.vtex.com/t/criar-uma-nova-aba-custom-em-vtex-my-account/26493/7
> Add "store" domain to my-account-extension-example messages

- CHANGELOG.md
- node/package.json
- node/yarn.lock
- react/components/Menu/index.tsx
- react/components/pages/Addresses.tsx
Added a scroll to top when user clicks on the edit address button.
On mobile, if a user had a number of addresses in a vertical list, when clicking to edit an address their browser scroll position would remain at the bottom of the page, wherever they were when they clicked.
This PR adds a simple scroll to top method to ensure that users are sent to the top of the page when they enter the address edit interface.
New version is linked here: https://myaccountscroll--worldwidegolf.myvtex.com/
Go to My Account / Addresses, add a few addresses if you don't have any already, go into mobile mode, and click on the EDIT button for an address somewhere lower in the page. You should be scrolled to the top so the Edit Address header is on screen after navigation occurs.
> Scroll to top when user edits an address

- CHANGELOG.md
- manifest.json
- react/components/Addresses/AddressForm.tsx
- react/components/pages/AddressEdit.tsx
- react/typings/global.d.ts
When editing an existing address the user should not be able to edit the country of this address.
For profile V2 addresses schema we can not change the country of an existing address because the schema is different per country so we are disabling this option when editing an address to be compliant with this structure.
Test at this workspace: https://country--dunnesstoresqa.myvtex.com/account#/addresses
You may need to relink the version from this branch.
Before:
https://github.com/vtex-apps/my-account/assets/67066494/31eb65cb-ceae-4bac-b407-7974ffe82ca6
After:
https://github.com/vtex-apps/my-account/assets/67066494/ffbc12e3-68de-4fcb-a386-67b7504fd186
> disable country when editing existing address
